### ISSUE TITLE
CloudFlare Support CAA

### ISSUE THREAD

**Issue by ahaw021** [SSLMate/caa_helper#45] opened 2017-06-06 11:07 UTC
https://www.cloudflare.com

**Comment by mannyamorim** [comment] 2017-06-06 11:56
Cloudflare CAA records are currently in a closed beta program and are not available to the general public yet.

**Comment by ahaw021** [comment] 2017-06-06 12:08
yeah Just saw that :( 

signed up for the beta though

**Comment by AGWA** [comment] 2017-06-07 16:40
Dupe of #41

**Closed by AGWA** 2017-06-07 16:40 UTC
